name: delivery

on:
  push:
    tags:
    - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install deps
      uses: bahmutov/npm-install@v1
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test --ci
    - name: Build
      run: yarn build
    - name: Publish
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
